language: python
python:
- 3.7
before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda3/bin:$PATH
- conda update --yes conda

install:
- conda env create --file=environment.yml
- source activate DeepForest_JointPrediction

env: TRAVIS=true

script:
  - cd DeepForest_JointPrediction/tests/
  - pytest DeepForest_JointPrediction/tests/
